import pyodbc
c = pyodbc.connect('DRIVER={SQL Server};SERVER=.;DATABASE=ACP_DataWarehose_Proyecciones;Trusted_Connection=yes;')
cursor = c.cursor()
cursor.execute("SELECT COUNT(*) FROM Bronce.Evaluacion_Pesos")
print("Bronce:", cursor.fetchone()[0])
cursor.execute("SELECT COUNT(*) FROM Silver.Fact_Evaluacion_Pesos")
print("Silver:", cursor.fetchone()[0])
cursor.execute("SELECT COUNT(*) FROM Gold.Mart_Pesos_Calibres")
print("Gold:", cursor.fetchone()[0])
c.close()
