import pyodbc
import time
import subprocess
import sys

def main():
    conn_str = 'DRIVER={SQL Server};SERVER=.;DATABASE=ACP_DataWarehose_Proyecciones;Trusted_Connection=yes;'
    c = pyodbc.connect(conn_str)
    c.autocommit = True
    cursor = c.cursor()

    facts_info = [
        {"name": "Fact_Conteo_Fenologico", "silver_table": "Silver.Fact_Conteo_Fenologico", "bronce_table": "Bronce.Conteo_Fruta", "cuarentena_source": "Bronce.Conteo_Fruta", "expected_rows": 5242820, "expected_cuar": 0},
        {"name": "Fact_Evaluacion_Vegetativa", "silver_table": "Silver.Fact_Evaluacion_Vegetativa", "bronce_table": "Bronce.Evaluacion_Vegetativa", "cuarentena_source": "Bronce.Evaluacion_Vegetativa", "expected_rows": 489220, "expected_cuar": 3661},
        {"name": "Fact_Tasa_Crecimiento_Brotes", "silver_table": "Silver.Fact_Tasa_Crecimiento_Brotes", "bronce_table": "Bronce.Tasa_Crecimiento_Brotes", "cuarentena_source": "Bronce.Tasa_Crecimiento_Brotes", "expected_rows": 242032, "expected_cuar": 930},  # Only Bronce-sourced cuarentena; the 1008 Silver-sourced ones are NOT regenerated by a facts-only run
        {"name": "Fact_Cosecha_SAP", "silver_table": "Silver.Fact_Cosecha_SAP", "bronce_table": "Bronce.Data_SAP", "cuarentena_source": "Bronce.Data_SAP", "expected_rows": 156811, "expected_cuar": 1110},
        {"name": "Fact_Fisiologia", "silver_table": "Silver.Fact_Fisiologia", "bronce_table": "Bronce.Fisiologia", "cuarentena_source": "Bronce.Fisiologia", "expected_rows": 44413, "expected_cuar": 0},
        {"name": "Fact_Induccion_Floral", "silver_table": "Silver.Fact_Induccion_Floral", "bronce_table": "Bronce.Induccion_Floral", "cuarentena_source": "Bronce.Induccion_Floral", "expected_rows": 37620, "expected_cuar": 2227},
        {"name": "Fact_Floracion", "silver_table": "Silver.Fact_Floracion", "bronce_table": "Bronce.Floracion", "cuarentena_source": "Bronce.Floracion", "expected_rows": 25276, "expected_cuar": 6},
        {"name": "Fact_Censo_Plantas", "silver_table": "Silver.Fact_Censo_Plantas", "bronce_table": "Bronce.Censo_Plantas", "cuarentena_source": "Bronce.Censo_Plantas", "expected_rows": 19089, "expected_cuar": 296},
        {"name": "Fact_Ciclos_Fenologicos", "silver_table": "Silver.Fact_Ciclos_Fenologicos", "bronce_table": "Bronce.Ciclos_Fenologicos", "cuarentena_source": "Bronce.Ciclos_Fenologicos", "expected_rows": 18236, "expected_cuar": 0},
        {"name": "Fact_Evaluacion_Pesos", "silver_table": "Silver.Fact_Evaluacion_Pesos", "bronce_table": "Bronce.Evaluacion_Pesos", "cuarentena_source": "Bronce.Evaluacion_Pesos", "expected_rows": 5915, "expected_cuar": 48},
        {"name": "Fact_Areas_Plantas", "silver_table": "Silver.Fact_areas_plantas", "bronce_table": "Bronce.Base_Plantas_Area", "cuarentena_source": "Bronce.Base_Plantas_Area", "expected_rows": 3865, "expected_cuar": 304},
        {"name": "Fact_Peladas", "silver_table": "Silver.Fact_Peladas", "bronce_table": "Bronce.Peladas", "cuarentena_source": "Bronce.Peladas", "expected_rows": 1730, "expected_cuar": 0},
        {"name": "Fact_Ciclo_Poda", "silver_table": "Silver.Fact_Ciclo_Poda", "bronce_table": "Bronce.Evaluacion_Calidad_Poda", "cuarentena_source": "Bronce.Evaluacion_Calidad_Poda", "expected_rows": 1460, "expected_cuar": 0},
        {"name": "Fact_Tareo", "silver_table": "Silver.Fact_Tareo", "bronce_table": "Bronce.Consolidado_Tareos", "cuarentena_source": "Bronce.Consolidado_Tareos", "expected_rows": 0, "expected_cuar": 0},
        {"name": "Fact_Telemetria_Clima", "silver_table": "Silver.Fact_Telemetria_Clima", "bronce_table": "Bronce.Telemetria_Clima", "cuarentena_source": "Bronce.Telemetria_Clima", "expected_rows": 0, "expected_cuar": 0}
    ]

    print("=== STAGE 1: VERIFYING CURRENT BASELINES ===")
    mismatch_found = False
    for fact in facts_info:
        cursor.execute(f"SELECT COUNT(*) FROM {fact['silver_table']}")
        current_rows = cursor.fetchone()[0]
        
        # Query cuarentena
        cursor.execute(f"SELECT COUNT(*) FROM MDM.Cuarentena WHERE Tabla_Origen = '{fact['cuarentena_source']}'")
        current_cuar = cursor.fetchone()[0]
        
        # Add special check for Fact_Tasa_Crecimiento_Brotes which might have quarantined rows logged with silver table name
        if fact['name'] == "Fact_Tasa_Crecimiento_Brotes":
            pass  # Silver-sourced cuarentena rows (1008) are NOT re-generated by a facts-only reproceso run
            
        print(f"{fact['name']}:")
        print(f"  Silver rows: {current_rows} (Expected: {fact['expected_rows']})")
        print(f"  Cuarentena:  {current_cuar} (Expected: {fact['expected_cuar']})")
        
        if current_rows != fact['expected_rows'] or current_cuar != fact['expected_cuar']:
            print("  [WARNING] Mismatch detected in current database versus expectations!")
            mismatch_found = True

    print("\n=== STAGE 2: RESETTING DATABASE ===")
    for fact in facts_info:
        print(f"Resetting {fact['name']}...")
        # Clean Silver
        try:
            cursor.execute(f"TRUNCATE TABLE {fact['silver_table']}")
        except Exception:
            cursor.execute(f"DELETE FROM {fact['silver_table']}")
            
        # Clean Cuarentena
        cursor.execute(f"DELETE FROM MDM.Cuarentena WHERE Tabla_Origen = '{fact['cuarentena_source']}'")
        if fact['name'] == "Fact_Tasa_Crecimiento_Brotes":
            pass  # Silver-sourced cuarentena rows are intentionally left; they come from a different pipeline phase
            
        # Reset Bronce state
        cursor.execute(f"UPDATE {fact['bronce_table']} SET Estado_Carga = 'CARGADO'")

    # Shrink transaction log to prevent LOG_BACKUP full errors during large parallel inserts
    print("Shrinking transaction log...")
    try:
        cursor.execute("ALTER DATABASE ACP_DataWarehose_Proyecciones SET RECOVERY SIMPLE")
        cursor.execute("DBCC SHRINKFILE (ACP_DataWarehose_Proyecciones_log, 1)")
        # Keep recovery model as SIMPLE for local development to avoid transaction log full errors
        # cursor.execute("ALTER DATABASE ACP_DataWarehose_Proyecciones SET RECOVERY FULL")
        print("Transaction log shrunk OK.")
    except Exception as e:
        print(f"WARNING: Could not shrink transaction log: {e}")
    
    print("Database reset complete.")
    c.close()

    # Build pipeline execution command
    fact_names = [f['name'] for f in facts_info]
    cmd = [
        r"d:/Proyecto2026/ACP_DWH/ACP Proyecciones/.venv/Scripts/python.exe",
        r"d:/Proyecto2026/ACP_DWH/ACP Proyecciones/ETL/pipeline.py",
        "--modo-ejecucion", "facts",
        "--sin-gold",
        "--facts"
    ] + fact_names

    print("\n=== STAGE 3: RUNNING PIPELINE ===")
    print(f"Command: {' '.join(cmd)}")
    start_time = time.time()
    
    result = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8')
    
    end_time = time.time()
    elapsed = end_time - start_time
    
    print("\n=== PIPELINE OUTPUT ===")
    print(result.stdout)
    if result.stderr:
        print("=== PIPELINE ERRORS ===")
        print(result.stderr)

    print(f"\nPipeline execution took: {elapsed:.2f} seconds")

    print("\n=== STAGE 4: POST-RUN VERIFICATION ===")
    c = pyodbc.connect(conn_str)
    cursor = c.cursor()

    report = []
    has_mismatch = False
    
    report.append("| Fact Name | Silver Baseline | Silver Post-Run | Cuar Baseline | Cuar Post-Run | Match? |")
    report.append("| --- | --- | --- | --- | --- | --- |")

    for fact in facts_info:
        cursor.execute(f"SELECT COUNT(*) FROM {fact['silver_table']}")
        post_rows = cursor.fetchone()[0]
        
        cursor.execute(f"SELECT COUNT(*) FROM MDM.Cuarentena WHERE Tabla_Origen = '{fact['cuarentena_source']}'")
        post_cuar = cursor.fetchone()[0]
        
        if fact['name'] == "Fact_Tasa_Crecimiento_Brotes":
            pass  # Silver-sourced cuarentena rows not counted in this verification scope

        rows_match = post_rows == fact['expected_rows']
        cuar_match = post_cuar == fact['expected_cuar']
        match_str = "[OK] YES" if (rows_match and cuar_match) else "[FAIL] NO"
        if not (rows_match and cuar_match):
            has_mismatch = True

        report.append(f"| {fact['name']} | {fact['expected_rows']:,} | {post_rows:,} | {fact['expected_cuar']:,} | {post_cuar:,} | {match_str} |")

    c.close()

    print("\n".join(report))
    
    if has_mismatch:
        print("\n[ERROR] One or more facts showed a count mismatch after the vectorized reload!")
        sys.exit(1)
    else:
        print("\n[SUCCESS] Vectorized facts successfully matched all baseline and quarantine counts!")
        sys.exit(0)

if __name__ == '__main__':
    main()
